In [9]:
#Import the data from csv file
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv("/home/niharika/Desktop/Machinelearning/mldata/advertising.csv")
x= data.iloc[:,[2,3]].values
y= data.iloc[:,4].values
data.head()


Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  \
0                     68.95   35     61833.90                256.09   
1                     80.23   31     68441.85                193.77   
2                     69.47   26     59785.94                236.50   
3                     74.15   29     54806.18                245.89   
4                     68.37   35     73889.99                225.58   

                           Ad Topic Line            City  Male     Country  \
0     Cloned 5thgeneration orchestration     Wrightburgh     0     Tunisia   
1     Monitored national standardization       West Jodi     1       Nauru   
2       Organic bottom-line service-desk        Davidton     0  San Marino   
3  Triple-buffered reciprocal time-frame  West Terrifurt     1       Italy   
4          Robust logistical utilization    South Manuel     0     Iceland   

             Timestamp  Clicked on Ad  
0  2016-03-27 00:53:11              0  
1  2016-04-04 01:39:02              0  
2  2016-03-13 20:35:42              0  
3  2016-01-10 02:31:19              0  
4  2016-06-03 03:36:18              0

In [10]:
#Split data into training data and testing data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)


In [11]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x = scaler.fit_transform(x)


In [14]:
#Fitting Logistic Regression to dataset
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train, y_train)


LogisticRegression()

In [13]:
#Predicting test set result
y_pred = classifier.predict(x_test)


In [6]:
#predicating train set result
y_train=classifier.predict(x)


In [7]:
#Test dataset
from sklearn import metrics
matrices= metrics.confusion_matrix(y_test,y_pred)
print("The matrix is:")
print(matrices)
accuracy= metrics.accuracy_score(y_test,y_pred)
print("The Acuuracy score is:")
print(accuracy)


The matrix is:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
The Acuuracy score is:
0.0


In [8]:
#train dataset
matrices= metrics.confusion_matrix(y,y_train)
print("The matrix is:")
print(matrices)
accuracy= metrics.accuracy_score(y,y_train)
print("The Acuuracy score is:")
print(accuracy)


The matrix is:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
The Acuuracy score is:
0.017
